### ISSUE TITLE
Empty cards

### ISSUE THREAD

**Issue by Xtrem777** [tapahob/BG2RadarOverlay#24] opened 2022-07-28 15:00 UTC
I installed latest EEex in BG2:EE, but after I run the radar overlay all I'm getting is empty cards whichever name I click.
Only other mod I installed is bubb_spell_menu_extended.

What am I doing wrong?

**Comment by tapahob** [comment] 2022-07-28 17:43
Hii @Xtrem777!

The Radar is completely mod-agnostic.
I would assume its either not 2.6 or you've downloaded not the latest release. 
Also, what language are you playing in? 
Did you copy the radar executable to the game folder?

There is a video about setting it up here - https://youtu.be/ceSuvPXkQXA?t=496 with the mods you are talking about

**Comment by Xtrem777** [comment] 2022-07-28 18:44
Hi. BG2:EE is latest from steam.
I downloaded it from here in github (top one in releases) and it says 2.0.4.7.
Language is english.
I copied the radar executable in the game folder.
I attached the log file
[radar.log](https://github.com/tapahob/BG2RadarOverlay/files/9213365/radar.log)
.

**Comment by tapahob** [comment] 2022-07-28 18:54
Thanks for reporting that, I see whats the problem is there, gotta fix it as soon as I can.
For now, please fallback to this release - https://github.com/tapahob/BG2RadarOverlay/releases/tag/2.0.4.5 it should be working

**Comment by Xtrem777** [comment] 2022-07-28 18:55
Will do. Thank you so much.
I will report if 2.0.4.5 solves it.

**Comment by tapahob** [comment] 2022-07-28 19:10
Can you post a screenshot of your "C:\SteamLibrary\steamapps\common\Baldur's Gate II Enhanced Edition\data" folder?
It seems like there are no files like 25DEFLT.BİF 25DİALOG.BİF 25EFFECT.BİF etc. And the should be there on a clean install

**Comment by Xtrem777** [comment] 2022-07-28 19:21
I think the problem is my TR keyboard. Log says ***.BİF with "İ" instead of "I".
Otherwise all the files are there.
I changed my language and keyboard to US and it still gave me empty cards.
![Untitled](https://user-images.githubusercontent.com/110184222/181620034-584554ea-07a8-48c0-8013-cea2e0df6a69.png)

**Comment by tapahob** [comment] 2022-07-28 19:27
No its sure not because of the keyboard layout.
I will update the release with more logging shortly, will see whats going on there

**Comment by Xtrem777** [comment] 2022-07-28 19:28
Ok. Thank you for solving it! I appreciate it.

**Comment by tapahob** [comment] 2022-07-28 19:54
Please try this one and attach the new log - https://github.com/tapahob/BG2RadarOverlay/releases/tag/2.0.4.8-alpha

**Comment by Xtrem777** [comment] 2022-07-28 19:58
IT'S WORKIIIING!
Thank you!

**Comment by tapahob** [comment] 2022-07-28 19:59
@Xtrem777 Please attach the log anyway - Im interested in what it has to say

**Comment by Xtrem777** [comment] 2022-07-28 20:00
Here:
[radar.log](https://github.com/tapahob/BG2RadarOverlay/files/9213763/radar.log)

**Comment by tapahob** [comment] 2022-07-28 20:02
Interesting, it seems it was sensitive to the backslash in file path:
`2022-07-28 22:58:07.5063 [DEBUG] BIF file wasn't found: C:/SteamLibrary/steamapps/common/Baldur's Gate II Enhanced Edition/data/25AMBSND.BİF
2022-07-28 22:58:07.5063 [DEBUG] There is a biff with such name: C:\SteamLibrary\steamapps\common\Baldur's Gate II Enhanced Edition\data\25AmbSnd.bif`

**Comment by tapahob** [comment] 2022-07-28 22:04
if the error get reproduced with other filetypes - please use this release - https://github.com/tapahob/BG2RadarOverlay/releases/tag/2.0.4.9

I didn't know Turkish (and some other languages) has special upper-casing rules so I accounted for that now for other filetypes too.

**Comment by Xtrem777** [comment] 2022-07-29 15:34
Yesterday I couldnt test the previous one extensively (it was too late at night) so it didnt crash but changed to last one (2049) and it's working perfectly after hours.

**Comment by tapahob** [comment] 2022-07-29 15:51
Oki, closing the issue  then

**Closed by tapahob** 2022-07-29 15:51 UTC
